/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ga4gh.starterkit.passport;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {

}
